import './globals.css'
import { Inter } from 'next/font/google'

import Navbar from './navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '{% .App.Name %}',
  description: 'Generated by: hof create supacode',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
				<div className="flex flex-col">
					<Navbar />
					<div className="main-content">
						{children}
					</div>
				</div>
			</body>
    </html>
  )
}
